#!/bin/bash
# Helal Control Center(HCC) By "M.Hanny Sabbagh", <hannysabbagh@hotmail.com>

# A set of functions to get themes,icons,hardware information..
themename() {
gsettings get org.gnome.desktop.interface gtk-theme | awk -F"'" '{print $2}'
}

# This function will grep the windows manager theme using gsettings, and will cut the output to make it like "Crux" not like "'Crux'" using awk.
windowstheme() {
gsettings get org.gnome.desktop.wm.preferences theme | awk -F"'" '{print $2}'
}

theme_list() {
ls -d /usr/share/themes/*/gtk-3.0 | awk -F"/" '{print $5}' 
}

fontname() {
gsettings get org.gnome.desktop.interface font-name | awk -F"'" '{print $2}'
}

wfontname() {
gsettings get org.gnome.desktop.wm.preferences titlebar-font | awk -F"'" '{print $2}'
}

icon_list() {
ls -d /usr/share/icons/*/index.theme | awk -F"/" '{print $5}' 
}

metacity_themes() {
ls -d /usr/share/themes/*/metacity-1 | awk -F"/" '{print $5}' 
}

display_manager() {
cat /etc/X11/default-display-manager | awk -F"/" '{print $4}'
}

currenticon() {
gsettings get org.gnome.desktop.interface icon-theme | awk -F"'" '{print $2}'
}

set_dm() {
if [ -f /usr/sbin/mdm ]; then
xterm -e "sudo dpkg-reconfigure mdm && sleep 3" &
elif [ -f /usr/sbin/lightdm ]; then
xterm -e "sudo dpkg-reconfigure lightdm && sleep 3" &
elif [ -f /usr/sbin/gdm ]; then
xterm -e "sudo dpkg-reconfigure gdm && sleep 3" &
fi
}

Vga_card() {
lspci|grep VGA | awk -F":" '{print $3}'
}

ethernet() {
lspci|grep Ethernet | awk -F":" '{print $3}'
}

cpu() {
cat /proc/cpuinfo|grep "model name" | awk -F":" '{print $2}'
}

optimus() {
xterm -e "
wget -P /tmp/kernel-3.9/ http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.9-raring/linux-image-3.9.0-030900-generic_3.9.0-030900.201304291257_i386.deb ;
wget -P /tmp/kernel-3.9/ http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.9-raring/linux-headers-3.9.0-030900_3.9.0-030900.201304291257_all.deb ;
wget -P /tmp/kernel-3.9/ http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.9-raring/linux-headers-3.9.0-030900-generic_3.9.0-030900.201304291257_i386.deb ;
sudo dpkg -i /tmp/kernel-3.9/*.deb ;
sudo apt-get install nvidia-319 ;
" &
}

avapackages() {
apt-cache dumpavail | grep Package | cut -d ' ' -f 2 > /tmp/available-packages
gedit /tmp/available-packages
sleep 1
rm /tmp/available-packages
}

installedpackages() {
dpkg --get-selections > /tmp/installed-packages
sort /tmp/installed-packages > /tmp/installed-packages2
gedit /tmp/installed-packages2 
sleep 1
rm /tmp/installed-packages
rm /tmp/installed-packages2
}

commands() {
awk '{print $1}' ~/.bash_history | sort | uniq -c | sort -rn | head -n 10 > /tmp/commands
gedit /tmp/commands
sleep 1
rm /tmp/commands
}

#export the functions to use them later.
export -f windowstheme
export -f themename
export -f currenticon
export -f cpu
export -f ethernet
export -f Vga_card
export -f set_dm
export -f display_manager
export -f theme_list 
export -f icon_list 
export -f metacity_themes
export -f fontname
export -f wfontname
export -f optimus
export -f avapackages
export -f installedpackages
export -f commands

#go to the home folder, useful when using dpkg-repack or listing recent commands or available packages..
cd /home/$USER/

#export gtkdialog variable.
GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<window title="Helal Control Center" icon-name="system" decorated="true" resizable="false" width-request="800">
   <vbox>

	<button use-stock="true" image-position="1" relief="2">
	<width>48</width>
	<label>Helal Control Center</label>
	<input file>"/usr/share/helal-control-center/images/helal-control-center.svg"</input>
	<action type="launch">About</action>
	</button>




<hbox space-expand="true" space-fill="true">


<text><label>Helps you to Manage and Customize your system easily.</label></text>


	</hbox>
<notebook tab-labels="Start|System|Desktop|Hardware|Programs" page="00" tab-hborder="20" tab-vborder="15" tab-pos="00" >
	<vbox>


		<frame System:>
		<hbox space-expand="true" space-fill="false">


		<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/firewall.svg"</input>
		<label>Firewall</label>
		<action>gufw &</action>
		</button>

		<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/software-sources.svg"</input>
		<label>Software sources</label>
		<action>gksu software-properties-gtk &</action>
		</button>


		<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/software-update.svg"</input>
		<label>Update manager </label>
		<action>update-manager &</action>
		</button> 



		<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/software-add.svg"</input>
		<label>Software center</label>
		<action>gksu sc &</action>
		</button>
</hbox>

		<hbox space-expand="true" space-fill="false">

		<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/power-management.svg"</input>
		<label>Power management</label>
		<action>gnome-control-center power &</action>
		</button>

		<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/time-date-settings.svg"</input>
		<label>Date & Time</label>
		<action>gnome-control-center datetime &</action>
		</button>

		<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/keyboard.svg"</input>
		<label>Keyboard</label>
		<action>gnome-control-center keyboard &</action>
		</button>

		<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/system-language.svg"</input>
		<label>System language</label>
		<action>/usr/bin/gnome-language-selector &</action>
		</button> 
		
	

</hbox></frame> 

<frame Settings:>


<hbox space-expand="true" space-fill="true">

	<button use-stock="true" image-position="2" relief="2">
	<width>48</width>
		<input file>"/usr/share/helal-control-center/images/printer.svg"</input>
	<label>Printer management</label>
	<action> system-config-printer</action>
	</button>

	<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/display.svg"</input>
		<label>Display manager</label>
		<action>gnome-control-center display &</action>
		</button>



		<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/sound-preferences.svg"</input>
		<label>Sound Settings</label>
		<action> gnome-control-center sound &</action>
		</button>

		<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/root.svg"</input>
		<label>Accessibility</label>
		<action>gnome-control-center universal-access &</action>
		</button> 
</hbox>

<hbox space-expand="true" space-fill="true">

	<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/hardware-info.svg"</input>
	<label>Hardware information</label>
	<action> hardinfo &</action>
	</button>

	<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/hardware.svg"</input>
	<label>Hard-Disk</label>
	<action> gnome-disks &</action>
	</button>



		<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/bluetooth.svg"</input>
		<label>Bluetooth</label>
		<action>gnome-control-center bluetooth &</action>
		</button> 


	<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/mouse.svg"</input>
	<label>Mouse settings</label>
	<action>gnome-control-center mouse &</action>
	</button>

</hbox>

<hbox space-expand="true" space-fill="true">


	

	<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/backup.svg"</input>
	<label>Backup settings</label>
	<action>gnome-control-center deja-dup &</action>
	</button> 


	<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/scanner.svg"</input>
	<label>Scanner</label>
	<action>simple-scan &</action>
	</button>

		<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/users-accounts.svg"</input>
		<label>Account managment</label>
		<action>users-admin &</action>
		</button>


	<button use-stock="true" image-position="2" relief="2">
		<width>48</width>
		<input file>"/usr/share/helal-control-center/images/system.svg"</input>
	<label>Customize look&feel</label>
	<action>gnome-tweak-tool &</action>
	</button>




</hbox>
</frame>




</vbox>

<vbox scrollable="true">



<frame Quick Managment:>



<hbox space-expand="true" space-fill="true">
<text> <label>You can manage your system quickly from here, click on what you want to do to do it :D</label> </text>
	
	<pixmap icon_size="6">
	<width>48</width>
	<input file>"/usr/share/helal-control-center/images/system.svg"</input>
	</pixmap>

</hbox>

<hbox space-expand="true" space-fill="true">
	<button use-stock="true" image-position="1" relief="2">
	<width>32</width>
	<label>Startup applications</label>
<input file>"/usr/share/helal-control-center/images/startup-applications.svg"</input>
	<action>gnome-session-properties & </action>
	</button>

	<button use-stock="true" image-position="1" relief="2">
	<width>32</width>
	<label>Modify applications menu</label>
<input file>"/usr/share/helal-control-center/images/edit-menu.svg"</input>
	<action>alacarte &</action>
	</button>





</hbox>


<hbox space-expand="true" space-fill="true">
	

	<button use-stock="true" image-position="1" relief="2">
	<width>32</width>
<input file>"/usr/share/helal-control-center/images/system-clean.svg"</input>
	<label>System cleanup</label>
	<action> xterm -e "sudo apt-get clean && sudo apt-get autoremove && sudo apt-get autoclean  && sleep 3" & </action>
	</button>

	<button use-stock="true" image-position="1" relief="2">
	<width>32</width>
	<input file>"/usr/share/helal-control-center/images/software-update.svg"</input>
	<label>Distribution upgrade</label>
	<action> xterm -e  "sudo apt-get update && sudo do-release-upgrade && sleep 3" &</action>
	</button>

<button use-stock="true" image-position="1" relief="2">
	<width>32</width>
	<label>List most used commands</label>
	<input file>"/usr/share/helal-control-center/images/installed-packages.svg"</input>
	<action>commands</action>
</button>
</hbox>


</frame>

<frame Display Manager:>
<hbox space-fill="true" space-expand="true">
<text><label>The display manager is the responsible application to log you in to Helal Linux at startup, you can change it from here, do this at your own risk, after clicking the button below and opening the terminal, click Tab key, press Enter, and choose your DM, and press Enter again.</label></text>

	<pixmap icon_size="6">
	<width>48</width>
	<input file>"/usr/share/helal-control-center/images/backup.svg"</input>
	</pixmap>
</hbox>
<hbox space-fill="true" space-expand="true">
<button>
	<label>Change DM</label>
<action>set_dm</action>
</button>	
</hbox>
</frame>

<frame Package Managment:>
<hbox space-fill="true" space-expand="true">
<button use-stock="true" image-position="1" relief="2">
	<width>32</width>
	<label>List all available packages</label>
	<input file>"/usr/share/helal-control-center/images/software-add.svg"</input>
	<action>avapackages</action>
</button>

	<button use-stock="true" image-position="1" relief="2">
	<width>32</width>
	<label>List all installed packages</label>
<input file>"/usr/share/helal-control-center/images/installed-packages.svg"</input>
	<action>installedpackages</action>
	</button>

	<button use-stock="true" image-position="1" relief="2">
	<width>32</width>
	<input file>"/usr/share/helal-control-center/images/package-upgrade.svg"</input>
	<label>Install all updates</label>
	<action>xterm -e "sudo apt-get update && sudo apt-get upgrade  && sleep 3" &</action>
	</button>
</hbox>

<hbox space-fill="true" space-expand="true">
<text><label>Here you can repackage installed packages agian without an internet connection, you will find packages at your home folder.</label></text>

	<pixmap icon_size="6">
	<width>48</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	</pixmap>
</hbox>
<hbox>
<entry>
	<variable>package</variable>
</entry>
<button>
	<label>Repackage</label>
	<action>fakeroot -u dpkg-repack $package</action>
</button>	
</hbox>
</frame>

<frame System Files:>
<text><label>Warning: playing with some stuff here may break your system, do this at your own risk.</label></text>
<button use-stock="true" image-position="4" relief="1">
	<label>/etc/hosts.deny</label>	
	<width>48</width>
	<action>gksu gedit /etc/hosts.deny &</action>
</button>

<button use-stock="true" image-position="4" relief="1">
	<label>/etc/lightdm/lightdm.conf</label>	
	<width>48</width>
	<action>gksu gedit /etc/lightdm/lightdm.conf &</action>
</button>

<button use-stock="true" image-position="4" relief="1">
	<label>/etc/X11/default-display-manager</label>	
	<width>48</width>
	<action>gksu gedit /etc/X11/default-display-manager &</action>
</button>

<button use-stock="true" image-position="4" relief="1">
	<label>/etc/fstab</label>	
	<width>48</width>
	<action>gksu gedit /etc/fstab &</action>
</button>

<button use-stock="true" image-position="4" relief="1">
	<label>/etc/apt/sources.list</label>	
	<width>48</width>
	<action>gksu gedit /etc/apt/sources.list &</action>
</button>
</frame>

</vbox>

<vbox scrollable="true">

<frame Appearance:>


<hbox space-expand="true" space-expand="true">


	<text xalign="2"><label>You can customize your desktop look&feel from here, you need an internet connection to download new themes.</label></text>

	<pixmap icon_size="6">
	<width>48</width>
	<input file>"/usr/share/helal-control-center/images/config-themes.svg"</input>
	</pixmap>
</hbox>


<hbox space-expand="true" space-fill="true">
  <text><label>Theme:</label></text>

<comboboxtext fs-folder="true" fs-title="true" file-monitor="true" auto-refresh="true">
		<input>themename</input>
		<input>theme_list</input> 
		<variable>COMBOBOX</variable>
		<action>gsettings set org.gnome.desktop.interface gtk-theme $COMBOBOX</action>
		</comboboxtext>

	<button>
	<label>Download themes</label>
	<width>32</width>
	<action>xdg-open http://gnome-look.org</action>
	<input file>/usr/share/helal-control-center/images/download-themes.svg</input>
</button>
</hbox>


<hbox space-expand="true" space-fill="true">
  		<text><label>Windows:</label></text>
		<comboboxtext fs-folder="true" fs-title="true" file-monitor="true" auto-refresh="true">
		<input>windowstheme</input>
		<input>metacity_themes</input> 
		<variable>metacity</variable>
		<action>gsettings set org.gnome.desktop.wm.preferences theme $metacity</action>
		</comboboxtext>

<button>
	<label>Download W-themes</label>
	<width>32</width>
	<action>xdg-open http://gnome-look.org</action>
	<input file>/usr/share/helal-control-center/images/download-themes.svg</input>
</button>
</hbox>


<hbox space-expand="true" space-fill="true">
	  <text><label>Icons:</label></text>
<comboboxtext fs-folder="true" fs-title="true" file-monitor="true" auto-refresh="true">
		<input>currenticon</input>
		<input>icon_list</input> 
		<variable>icons</variable>
		<action>gsettings set org.gnome.desktop.interface icon-theme $icons</action>
		</comboboxtext>
<button>
	<label>Download icons</label>
	<width>32</width>
	<action>xdg-open http://gnome-look.org</action>
	<input file>/usr/share/helal-control-center/images/download-themes.svg</input>
</button>
</hbox>

</frame>

<hbox space-expand="true" space-fill="true">
<frame Desktop icons:>




<checkbox auto-refresh="true">
	<label>Show icons</label>
	<input>gsettings get org.gnome.desktop.background show-desktop-icons</input>
	<action>if true gsettings set org.gnome.desktop.background show-desktop-icons true</action>
	<action>if false gsettings set org.gnome.desktop.background show-desktop-icons false</action>
</checkbox>

<checkbox auto-refresh="true">
	<label>Home icon</label>
	<input>gsettings get org.gnome.nautilus.desktop home-icon-visible</input>
	<action>if true gsettings set org.gnome.nautilus.desktop home-icon-visible true</action>
	<action>if false gsettings set org.gnome.nautilus.desktop home-icon-visible false</action>
</checkbox>

<checkbox auto-refresh="true">
	<label>Network icon</label>
	<input>gsettings get org.gnome.nautilus.desktop network-icon-visible</input>
	<action>if true gsettings set org.gnome.nautilus.desktop network-icon-visible true</action>
	<action>if false gsettings set org.gnome.nautilus.desktop network-icon-visible false</action>
</checkbox>

<checkbox auto-refresh="true">
	<label>Trash icon</label>
	<input>gsettings get org.gnome.nautilus.desktop trash-icon-visible</input>
	<action>if true gsettings set org.gnome.nautilus.desktop trash-icon-visible true</action>
	<action>if false gsettings set org.gnome.nautilus.desktop trash-icon-visible false</action>
</checkbox>

<checkbox auto-refresh="true">
	<label>Removeable disks</label>
	<input>gsettings get org.gnome.nautilus.desktop volumes-visible</input>
	<action>if true gsettings set org.gnome.nautilus.desktop volumes-visible true</action>
	<action>if false gsettings set org.gnome.nautilus.desktop volumes-visible false</action>
</checkbox>

</frame>

<frame File Manager:>

	<checkbox auto-refresh="true">
	<label>Display the sidebar</label>
	<input>$test</input>
	<action>if true gsettings set org.gnome.nautilus.window-state start-with-sidebar true</action>
	<action>if false gsettings set org.gnome.nautilus.window-state start-with-sidebar false</action>
</checkbox>

<checkbox auto-refresh="true">
	<label>Always show loction entry</label>
	<input>gsettings get org.gnome.nautilus.preferences always-use-location-entry</input>
	<action>if true gsettings set org.gnome.nautilus.preferences always-use-location-entry true</action>
	<action>if false gsettings set org.gnome.nautilus.preferences always-use-location-entry false</action>
</checkbox>

<checkbox auto-refresh="true">
	<label>Show hidden files</label>
	<input>gsettings get org.gnome.nautilus.preferences show-hidden-files</input>
	<action>if true gsettings set org.gnome.nautilus.preferences show-hidden-files true</action>
	<action>if false gsettings set org.gnome.nautilus.preferences show-hidden-files false</action>
</checkbox>

<checkbox auto-refresh="true">
	<label>Sort folders first</label>
	<input>gsettings get org.gnome.nautilus.preferences sort-directories-first</input>
	<action>if true gsettings set org.gnome.nautilus.preferences sort-directories-first true</action>
	<action>if false gsettings set org.gnome.nautilus.preferences sort-directories-first false</action>
</checkbox>


</frame>
</hbox>

<frame Manage Fonts:>
<hbox space-expand="true" space-fill="true">
	<text><label>You can customize and manage fonts from here.</label></text>

	<pixmap icon_size="6">
	<width>48</width>
	<input file>"/usr/share/helal-control-center/images/fonts-download.svg"</input>
	</pixmap>
</hbox>

<hbox>
<text><label>Default Font:</label></text>

<fontbutton space-expand="true" space-fill="true">
	<input>fontname</input>
	<variable>font</variable>
	<action>gsettings set org.gnome.desktop.interface font-name "$font"</action>
</fontbutton>
</hbox>

<hbox>
<text><label>Title Font:</label></text>

<fontbutton space-expand="true" space-fill="true">
	<input>wfontname</input>
	<variable>font2</variable>
	<action> gsettings set org.gnome.desktop.wm.preferences titlebar-font "$font2"</action>
</fontbutton>
</hbox>

</frame>

<frame Helal Backup:>

<hbox space-expand="true" space-fill="true">


<text><label>You can backup your Settings/Themes folders in your home directory, choose where to save the file.</label></text>
	<pixmap>
	<width>48</width>
	<input file>/usr/share/helal-control-center/images/system-recovery.svg</input>
	</pixmap>
</hbox>



<hbox>
<entry accept="directory">
        	  <label>Save in:</label>
		  <default>/home/'$USER'</default>
        	  <variable>FILE_DIRECTORY</variable>
      		 </entry>

      		<button>
        	  <input file stock="gtk-open"></input>
        	  <action type="fileselect">FILE_DIRECTORY</action>
      		</button>

<button use-stock="true" image-position="1" relief="1">
	<width>32</width>
	<variable>backup</variable>
	<input file>/usr/share/helal-control-center/images/backup.svg</input>
	<label>Backup</label>
<action>mkdir /home/$USER/hbackup</action>
<action>cp -R /home/$USER/hbackup files</action>
<action>cp -R /home/$USER/.cache files</action>
<action>cp -R /home/$USER/.fonts files</action>
<action>cp -R /home/$USER/.gnome2 files</action>
<action>cp -R /home/$USER/.gconf files</action>
<action>cp -R /home/$USER/.gimp-2.6 files</action>
<action>cp -R /home/$USER/.gimp-2.8 files</action>
<action>cp -R /home/$USER/.gnupg files</action>
<action>cp -R /home/$USER/.local files</action>
<action>cp -R /home/$USER/.mozilla files</action>
<action>cp -R /home/$USER/.pulse files</action>
<action>cp -R /home/$USER/.dbus files</action>
<action>cp -R /home/$USER/.icons files</action>
<action>cp -R /home/$USER/.config files</action>
<action>cp -R /home/$USER/.themes files</action>
<action>chmod -R 777 files</action>
<action>tar -cf $FILE_DIRECTORY/h-backup.zip files</action>
<action>rm -R files</action>


	</button>

</hbox>


</frame>

</vbox>


<vbox scrollable="true">
<frame VGA Card:>

<hbox space-fill="true" space-expand="true">

<text> <label>Choose your VGA type to install the closed-source driver, you need an internet connection to do this.</label> </text>

	<pixmap>
	<width>48</width>
	<input file>"/usr/share/helal-control-center/images/hardware.svg"</input>
	</pixmap>

</hbox>

<hbox space-expand="true" space-fill="false">
	<button use-stock="true" image-position="2" relief="2">
	<width>32</width>
	<input file>"/usr/share/helal-control-center/images/nvidia.svg"</input>
	<label>Nvidia</label>
	<action>xterm -e "sudo apt-get install nvidia-current && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="2" relief="2">
	<width>32</width>
	<input file>"/usr/share/helal-control-center/images/ati.svg"</input>
	<label>ATI</label>
	<action>xterm -e "sudo apt-get install fglrx && sleep 3"</action>

	</button>

</hbox>
</frame>

<frame Nvidia Optimus Support:>
<hbox space-fill="true" space-expand="true">

<text> <label>Here you can install Nvidia Optimus support on your computer, you need an internet, dont do this if you dont have a Nvidia Optimus.</label> </text>

	<pixmap>
	<width>48</width>
	<input file>"/usr/share/helal-control-center/images/optimus.png"</input>
	</pixmap>

</hbox>

<hbox space-fill="true" space-expand="true">
	<button use-stock="true" image-position="2" relief="2">
	<width>32</width>
	<input file>'/usr/share/helal-control-center/images/nvidia.svg'</input>
	<label>Support Nvidia Optimus</label>
	<action>optimus</action>

	</button>

</hbox>
</frame>

<frame Hardware:>

<hbox space-fill="true" space-expand="true">

<text><label>Here you can view your hardware information, beside some network options.</label></text>

<pixmap icon_size="6">
	<width>48</width>
	<input file>"/usr/share/helal-control-center/images/hardware-info.svg"</input>
	</pixmap>


</hbox>


<hbox space-expand="true" space-fill="true"><text><label>CPU:</label></text></hbox>
<hbox>

<text selectable="true"  width-request="400">

	<input>cpu</input>
</text>

</hbox>

<hbox space-expand="true" space-fill="true"><text><label>VGA:</label></text></hbox>
<hbox>

<text selectable="true" width-request="400">

	<input>Vga_card</input>
</text>

</hbox>

<hbox space-expand="true" space-fill="true"><text><label>Network:</label></text></hbox>
<hbox>

<text selectable="true" width-request="400">

	<input>ethernet</input>
</text>

</hbox>
<hbox space-expand="true" space-fill="true"><text><label>Sound:</label></text></hbox>
<hbox>

<text selectable="true" width-request="400">

	<input>lspci|grep Audio</input>
</text>

</hbox>




<hbox space-fill="true" space-expand="true">



<button use-stock="true" image-position="4" relief="1">
	<input file>'/usr/share/helal-control-center/images/hardware-info.svg'</input>
	<label>More details</label>	
	<width>48</width>
	<action>hardinfo &</action>
</button>

<button use-stock="true" image-position="4" relief="1">
	<label>Copy to a file</label>
	<input file>'/usr/share/helal-control-center/images/copy-hardware-info-text.svg'</input>
	<width>48</width>
	<action>cat /proc/cpuinfo|grep "model name" >> /tmp/hardware</action>
<action>echo "-------------------------" >> /tmp/hardware</action>
<action>lspci|grep Audio >> /tmp/hardware</action>
<action>echo "-------------------------" >> /tmp/hardware</action>
<action>lspci|grep VGA >> /tmp/hardware</action>
<action>echo "-------------------------" >> /tmp/hardware</action>
<action>lspci|grep Ethernet && lspci|grep Network >> /tmp/hardware</action>
<action>echo "-------------------------" >> /tmp/hardware</action>
<action>lspci|grep Audio >> /tmp/hardware</action>
<action>gedit /tmp/hardware</action>	
<action>sleep 1</action>
<action>rm /tmp/hardware</action>

</button>
	
</hbox>
</frame>


<frame Internet:>

<hbox space-fill="true" space-expand="true">
<text><label>Network manager is the program that allows you to connect to the internet, you can configure its options from here.</label></text>

	<pixmap icon_size="6">
	<width>48</width>
	<input file>"/usr/share/helal-control-center/images/networking.svg"</input>
	</pixmap>

</hbox>

<hbox space-fill="true" space-expand="true">


	<button use-stock="true" image-position="4" relief="1">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/network-editor.svg"</input>
	<label>manage connections</label>
	<action>nm-connection-editor &</action>
	</button>

	<button use-stock="true" image-position="4" relief="1">
	<width>24</width>
	<input file>'/usr/share/helal-control-center/images/network-settings.svg'</input>
	<label>Install windows drivers</label>
	<action>gksu /usr/sbin/ndisgtk &</action>
	</button>
</hbox>

<hbox space-fill="true" space-expand="true">

	<button use-stock="true" image-position="4" relief="1">
	<width>24</width>
	<input file>'/usr/share/helal-control-center/images/site-block.svg'</input>
	<label>Block bad websites</label>
	<action>mintnanny &</action>
	</button>

<button use-stock="true" image-position="4" relief="1">
	<width>24</width>
	<input file>'/usr/share/helal-control-center/images/windows-share.svg'</input>
	<label>Windows share</label>
	<action>gksu system-config-samba &</action>
	</button>

</hbox>
	

	


</frame>





</vbox>


<vbox>

<hbox space-fill="true" space-expand="true">
<text><label>Here you will find a cool set of programs ready to install directly, you need an internet connection to install them.</label></text>

	<pixmap>
	<width>48</width>
	<input file>/usr/share/helal-control-center/images/software-add.svg</input>
	</pixmap>
</hbox>

<frame Miscellaneous:>
<hbox space-fill="true" space-expand="true">

	<button use-stock="true" image-position="4" relief="2" tooltip-text="KDE package management tool using PackageKit">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Apper</label>
	<action>xterm -e "sudo apt-get install apper && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="A Display Manager for LXDE">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>LXDM</label>
	<action>xterm -e "sudo apt-get install lxdm && sleep 3"</action>
	<action>/tmp/run</action>
	</button>


	<button use-stock="true" image-position="4" relief="2" tooltip-text="desktop-independent graphical login manager for X11">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Slim</label>
	<action>xterm -e "sudo apt-get install slim && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="fast processor emulator">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Qemu</label>
	<action>xterm -e "sudo apt-get install qemu && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="extremely fast and lightweight file manager">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Pcmanfm</label>
	<action>xterm -e "sudo apt-get install pcmanfm && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="universal document viewer">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Okular</label>
	<action>xterm -e "sudo apt-get install okular && sleep 3"</action>

	</button>
</hbox>
<hbox space-fill="true" space-expand="true">

	<button use-stock="true" image-position="4" relief="2" tooltip-text="efficient, featureful word processor with collaboration">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Abiword</label>
	<action>xterm -e "sudo apt-get install abiword && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="International dictionary">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Stardict</label>
	<action>xterm -e "sudo apt-get install stardict && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="project management application">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Planner</label>
	<action>xterm -e "sudo apt-get install planner && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="Quickly perform actions on your desktop">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Gnome do</label>
	<action>xterm -e "sudo apt-get install gnome-do && sleep 3"</action>

	</button>

</hbox>
</frame>

<frame Games:>
<hbox space-fill="true" space-expand="true">

	<button use-stock="true" image-position="4" relief="2"  tooltip-text="3D real time strategy game">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Warzone2100</label>
	<action>xterm -e "sudo apt-get install warzone2100 && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="Real-time strategy game of ancient warfare">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>0.AD</label>
	<action>xterm -e "sudo apt-get install 0ad && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="cool game where you pop out the bubbles!">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>frozen-bubble</label>
	<action>xterm -e "sudo apt-get install frozen-bubble && sleep 3"</action>

	</button>

</hbox>
<hbox space-fill="true" space-expand="true">

	<button use-stock="true" image-position="4" relief="2" tooltip-text="">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Supertux</label>
	<action>xterm -e "sudo apt-get install supertux && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="naval battle game for KDE">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>navalbattle</label>
	<action>xterm -e "sudo apt-get install knavalbattle && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2"  tooltip-text="front-end for Wine to install windows software easily">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Playonlinux</label>
	<action>xterm -e "sudo apt-get install playonlinux && sleep 3"</action>

	</button>


</hbox>
</frame>

<frame GUIs:>
<hbox space-fill="true" space-expand="true">

	<button use-stock="true" image-position="4" relief="2" tooltip-text="MATE is a fork of gnome 2.x">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>MATE</label>
	<action>xterm -e "sudo apt-get install mate-desktop-environment && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="Interface designed for efficiency of space and interaction">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Xfce</label>
	<action>xterm -e "sudo apt-get install xfce4 && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="Innovative and comfortable desktop">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Cinnamon</label>
	<action>xterm -e "sudo apt-get install cinnamon && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="The famous K Desktop Environment">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>KDE</label>
	<action>xterm -e "sudo apt-get install kubuntu-desktop && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="Lightweight X11 Desktop Environment">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>LXDE</label>
	<action>xterm -e "sudo apt-get install lxde && sleep 3"</action>

	</button>


</hbox>
</frame>
<frame Internet:>
<hbox space-fill="true" space-expand="true">

	<button use-stock="true" image-position="4" relief="2"  tooltip-text="The Chromium browser">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Firefox</label>
	<action>xterm -e "sudo apt-get install firefox && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2"  tooltip-text="fast, lightweight graphical web browser">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Midori</label>
	<action>xterm -e "sudo apt-get install midori && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2"  tooltip-text="instant messaging client">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Emesene</label>
	<action>xterm -e "sudo apt-get install emesene && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2"  tooltip-text="MSN messenger application written in Tcl">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Amsn</label>
	<action>xterm -e "sudo apt-get install amsn && sleep 3"</action>

	</button>
</hbox>

<hbox space-fill="true" space-expand="true"  tooltip-text="Email, RSS and newsgroup client with integrated spam filter">
	<button use-stock="true" image-position="4" relief="2">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>MozillaThunderbird</label>
	<action>xterm -e "sudo apt-get install thunderbird && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="download manager for KDE">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>kget</label>
	<action>xterm -e "sudo apt-get install kget && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="KDE micro-blogging client">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Choqok</label>
	<action>xterm -e "sudo apt-get install choqok && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2" tooltip-text="Fast and secure web browser and Internet suite">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Opera</label>
	<action>xterm -e "sudo apt-get install opera && sleep 3"</action>

	</button>

	<button use-stock="true" image-position="4" relief="2"  tooltip-text="network traffic analyzer">
	<width>24</width>
	<input file>"/usr/share/helal-control-center/images/package.png"</input>
	<label>Wireshark</label>
	<action>xterm -e "sudo apt-get install wireshark && sleep 3"</action>

	</button>



</hbox>
</frame>


</vbox>

</notebook>

	</vbox>

</window>
'
export About='

<window title="About" icon-name="gtk-about" resizable="true" border-width="3">
<notebook tab-labels="About|Developers" page="00" tab-hborder="20" tab-pos="00" >
   <vbox>	

	<pixmap>
        <width>96</width>
        <input file>'"/usr/share/helal-control-center/images/helal-control-center.svg"'</input>
        </pixmap>

<text>
<label>A Control Center for Helal Linux</label>

</text>

   </vbox>

<vbox>
<text><label>Programmed by:</label></text>
<text><label>M.Hanny Sabbagh hannysabbagh@hotmail.com </label></text>
<text><label>Artwork by:</label></text>
<text><label>Mustapha Asbbasr mustaphaasbbasr@gmail.com</label></text>
<text><label>Saif Alislam Albakry albakry@gmail.com </label></text>
</vbox>
</notebook>
</window>
'

#run the MAIN_DIALOG variable and put it to the center.
gtkdialog -p MAIN_DIALOG --center
